jobGroups:
  ai_intern:
    label: AI实习生
    jobTypes:
      - AI应用开发实习生
  operation_ab:
    label: 运营A/B
    jobTypes:
      - 运营A
      - 运营B
  strategic_direct:
    label: AI/财务/投资直求简历
    jobTypes:
      - AI智能体解决方案负责人
      - 外部财务产品顾问
      - 投资交易策略研究员（量化与市场情绪方向）
      - AI产品经理

members:
  - names:
      - 马弘毅
    jobGroups:
      - ai_intern
  - names:
      - 佘欣平
      - 佘新平
      - 杨梅
    jobGroups:
      - operation_ab
  - names:
      - 张怀滨
    jobGroups:
      - strategic_direct
  - openIds:
      - ou_acadfb85356a318fb1fc168be8fbfb75
    jobTypes:
      - AI产品经理
  - openIds:
      - ou_64e5196c8a8c4563ffa1659415188e98
    jobTypes:
      - AI智能体解决方案负责人
      - AI产品经理
  - openIds:
      - ou_e14f45b5432a8a67e091916e43503a14
    jobTypes:
      - AI智能体解决方案负责人
      - AI产品经理
